------------- 공지사항 테이블 ----------------
CREATE TABLE BOARD (
	IDX	NUMBER	NOT NULL ,
	A_ID VARCHAR2(20)	NOT NULL,
	TITLE VARCHAR2(100)	NOT NULL,
	CONTENT	CLOB NOT NULL,
	B_DATE	DATE DEFAULT SYSDATE NOT NULL,
	FILE_NAME	VARCHAR2(100)	NULL,
	ORI_NAME	VARCHAR2(100)	NULL,
	HIT	NUMBER	DEFAULT 0 NULL,
    CONSTRAINT BOARD_PK PRIMARY KEY(IDX),
    CONSTRAINT BOARD_FK FOREIGN KEY(A_ID) REFERENCES ADMIN(A_ID)
);
COMMENT ON TABLE BOARD IS '공지사항';
COMMENT ON COLUMN BOARD.IDX IS '번호';
COMMENT ON COLUMN BOARD.A_ID IS '관리자아이디';
COMMENT ON COLUMN BOARD.TITLE IS '제목';
COMMENT ON COLUMN BOARD.CONTENT IS '내용';
COMMENT ON COLUMN BOARD.B_DATE IS '작성일';
COMMENT ON COLUMN BOARD.FILE_NAME IS '실제파일명';
COMMENT ON COLUMN BOARD.ORI_NAME IS '원본파일명';
COMMENT ON COLUMN BOARD.HIT IS '조회수';

SELECT * FROM BOARD;
-------- 관리자 테이블 --------
CREATE TABLE ADMIN (
	A_ID	VARCHAR2(20) NOT NULL ,
	PASSWORD	VARCHAR2(20)	NULL,
	A_NAME	VARCHAR2(20)	NULL,
    CONSTRAINT ADMIN_PK PRIMARY KEY(A_ID)
);
COMMENT ON TABLE ADMIN IS '관리자';
COMMENT ON COLUMN ADMIN.A_ID IS '관리자아이디';
COMMENT ON COLUMN ADMIN.PASSWORD IS '관리자비밀번호';
COMMENT ON COLUMN ADMIN.A_NAME IS '관리자이름';



--------문의사항-------
CREATE TABLE QUESTIONS (
	Q_IDX	NUMBER	NOT NULL,
	EMAIL	VARCHAR2(50) NOT NULL,
	NAME	VARCHAR2(20) NOT NULL,
	PHONE	VARCHAR2(20) NOT NULL,
	MEMBER_TYPE	VARCHAR2(20) NOT NULL,
	TYPE_INQRY	NUMBER NOT NULL,
	Q_TITLE	VARCHAR2(100) NOT NULL,
	Q_CONTENT CLOB NOT NULL,
	Q_DATE	 DATE DEFAULT SYSDATE NOT NULL,
	FILE_NAME	VARCHAR2(100) NULL,
	ORI_NAME	VARCHAR2(100) NULL,
    CONSTRAINT QUESTIONS_PK PRIMARY KEY(Q_IDX)
);
COMMENT ON TABLE QUESTIONS IS '문의사항';
COMMENT ON COLUMN QUESTIONS.Q_IDX IS '번호';
COMMENT ON COLUMN QUESTIONS.EMAIL IS '이메일';
COMMENT ON COLUMN QUESTIONS.NAME IS '이름';
COMMENT ON COLUMN QUESTIONS.PHONE IS '전화번호';
COMMENT ON COLUMN QUESTIONS.MEMBER_TYPE IS '회원유형';
COMMENT ON COLUMN QUESTIONS.TYPE_INQRY IS '문의유형';
COMMENT ON COLUMN QUESTIONS.Q_TITLE IS '제목';
COMMENT ON COLUMN QUESTIONS.Q_CONTENT IS '내용';
COMMENT ON COLUMN QUESTIONS.Q_DATE IS '작성일';
COMMENT ON COLUMN QUESTIONS.FILE_NAME IS '실제파일명';
COMMENT ON COLUMN QUESTIONS.ORI_NAME IS '원본파일명';

    

------- 가이드 ----------
CREATE TABLE GUIDE (
	G_IDX	NUMBER	NOT NULL,
	A_ID	VARCHAR2(20)	NOT NULL,
	G_TITLE	VARCHAR2(100)	NOT NULL,
	G_CONTENT	CLOB	NOT NULL,
	TYPE VARCHAR2(10) NOT	NULL,,
	FILE_NAME	VARCHAR2(100)	NULL,
	ORI_NAME	VARCHAR2(100)	NULL,
    CONSTRAINT GUIDE_PK PRIMARY KEY(G_IDX),
    CONSTRAINT GUIDE_FK FOREIGN KEY(A_ID) REFERENCES ADMIN(A_ID)
);
COMMENT ON TABLE GUIDE IS '가이드';
COMMENT ON COLUMN GUIDE.G_IDX IS '번호';
COMMENT ON COLUMN GUIDE.A_ID IS '관리자아이디';
COMMENT ON COLUMN GUIDE.G_TITLE IS '제목';
COMMENT ON COLUMN GUIDE.G_CONTENT IS '내용';
COMMENT ON COLUMN GUIDE.TYPE IS '유형';
COMMENT ON COLUMN GUIDE.FILE_NAME IS '실제파일명';
COMMENT ON COLUMN GUIDE.ORI_NAME IS '원본파일명';


CREATE TABLE FRQNTASKQS (
	F_IDX	NUMBER	NOT NULL,
	A_ID	VARCHAR2(20)	NOT NULL,
	Q_IDX	NUMBER	NOT NULL,
	F_TITLE	VARCHAR2(100) NOT NULL,
	F_CONTENT	CLOB NOT NULL,
	FILE_NAME	VARCHAR2(100)	NULL,
	ORI_NAME	VARCHAR2(100)	NULL,
    CONSTRAINT FRQNTASKQS_PK PRIMARY KEY(F_IDX),
    CONSTRAINT FRQNTASKQS_FK FOREIGN KEY(A_ID) REFERENCES ADMIN(A_ID),
    CONSTRAINT FRQNTASKQS_FK2 FOREIGN KEY(Q_IDX) REFERENCES QUESTIONS(Q_IDX)
);
COMMENT ON TABLE FRQNTASKQS IS '자주묻는질문';
COMMENT ON COLUMN FRQNTASKQS.F_IDX IS '번호';
COMMENT ON COLUMN FRQNTASKQS.A_ID IS '관리자아이디';
COMMENT ON COLUMN FRQNTASKQS.Q_IDX IS '문의번호';
COMMENT ON COLUMN FRQNTASKQS.F_TITLE IS '제목';
COMMENT ON COLUMN FRQNTASKQS.F_CONTENT IS '내용';
COMMENT ON COLUMN FRQNTASKQS.FILE_NAME IS '실제파일명';
COMMENT ON COLUMN FRQNTASKQS.ORI_NAME IS '원본파일명';

---고객센터 및 관리자 부분 시퀀스
CREATE SEQUENCE FRQNTASKQS_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999
    NOCACHE;

CREATE SEQUENCE BOARD_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999
    NOCACHE;

CREATE SEQUENCE QUESTIONS_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999
    NOCACHE;

CREATE SEQUENCE GUIDE_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999
    NOCACHE;

COMMIT;

--부모회원 테이블
CREATE TABLE "DOLBOM"."MEMBER" 
   (   "USERID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "TYPE" NUMBER, 
   "PWD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "PWD2" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "NAME" VARCHAR2(20 BYTE), 
   "PHONE" VARCHAR2(20 BYTE), 
   "BIRTH" NUMBER, 
   "ADDRESS" VARCHAR2(50 BYTE), 
   "EMAIL" VARCHAR2(50 BYTE), 
   "CHILD_AGE" NUMBER, 
   "CARE" NUMBER, 
   "PAY" NUMBER, 
    CONSTRAINT "USER_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


